#!/usr/bin/env bash

#=================================================
# compile and setup runtime context
#=================================================

cd ../../cmt
cmt bro make || eval 'echo VALIDATION BUILD FAILED ; exit' ;
make test || eval 'echo VALIDATION BUILD FAILED ; exit' ;
. setup.sh
cd ../src/test

#=================================================
# write job
#=================================================

rm -f *-fake.root writeHeaders.log
test_RootIo.exe writeHeadersOptions.txt | grep -E '^FhDemoGetAlg' >| writeHeaders.log
diff -q -s writeHeaders.log writeHeaders.ref || eval 'echo VALIDATION DIFF FAILED ; exit' ;


#=================================================
# read job
#=================================================

rm -f readHeaders.log
test_RootIo.exe readHeadersOptions.txt | grep -E '^FhDemoGetAlg' >| readHeaders.log
diff -q -s readHeaders.log readHeaders.ref || eval 'echo VALIDATION DIFF FAILED ; exit' ;

#=================================================
# end
#=================================================

echo Everything OK

